/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package progressbarextended;

import javax.swing.JLabel;
import javax.swing.JSlider;

/**
 *
 * @author benmu
 */
public class ProgressBarPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProgressBarPanel
     */
    public ProgressBarPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSliderNivel1 = new javax.swing.JSlider();
        jSliderNivel2 = new javax.swing.JSlider();
        jLabelNivel1 = new javax.swing.JLabel();
        jLabelNivel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jSliderNivel1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderNivel1StateChanged(evt);
            }
        });

        jSliderNivel2.setValue(75);
        jSliderNivel2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderNivel2StateChanged(evt);
            }
        });

        jLabelNivel1.setText("50%");

        jLabelNivel2.setText("75%");

        jLabel3.setText("Rango 1:");

        jLabel4.setText("Rango 2:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(30, 30, 30)
                        .addComponent(jSliderNivel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSliderNivel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelNivel1)
                    .addComponent(jLabelNivel2))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSliderNivel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNivel1)
                    .addComponent(jLabel3))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSliderNivel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNivel2)
                    .addComponent(jLabel4))
                .addContainerGap(110, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jSliderNivel1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderNivel1StateChanged
        // TODO add your handling code here:
        mostrarValores(jLabelNivel1,jSliderNivel1);
        if (jSliderNivel1.getValue()>=jSliderNivel2.getValue()) 
        {
            jSliderNivel2.setValue(jSliderNivel1.getValue());
             mostrarValores(jLabelNivel1,jSliderNivel1);
                    
                    }
        mostrarValores(jLabelNivel1,jSliderNivel1);
    }//GEN-LAST:event_jSliderNivel1StateChanged

    private void jSliderNivel2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderNivel2StateChanged
        // TODO add your handling code here:
        mostrarValores(jLabelNivel2,jSliderNivel2);
        if (jSliderNivel2.getValue()<=jSliderNivel1.getValue()) 
        {
            jSliderNivel1.setValue(jSliderNivel2.getValue());
             mostrarValores(jLabelNivel2,jSliderNivel2);
                    
                    }
        mostrarValores(jLabelNivel2,jSliderNivel2);
    }//GEN-LAST:event_jSliderNivel2StateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelNivel1;
    private javax.swing.JLabel jLabelNivel2;
    private javax.swing.JSlider jSliderNivel1;
    private javax.swing.JSlider jSliderNivel2;
    // End of variables declaration//GEN-END:variables

public Rangos getSelectedValue(){
        return new Rangos(jSliderNivel1.getValue(), jSliderNivel2.getValue());
  }

void mostrarValores(JLabel label, JSlider slider){
    label.setText(String.valueOf(slider.getValue())+"%");
  }
}


