/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package u04_usabilidad02;

import java.awt.event.KeyEvent;
import java.awt.Color;
import java.awt.Component;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author portatil_profesorado
 */
public class IntroducirReforma extends javax.swing.JDialog {

    /**
     * Creates new form IntroducirReforma
     */
    public IntroducirReforma(java.awt.Frame parent, boolean modal) {
        
        super(parent, modal);
        
        initComponents();
        
        this.setLocationRelativeTo(null);
       
        getContentPane().setBackground(new Color(255, 255, 255));
        
        ImageIcon imagen=new ImageIcon("recursos/EJ01_02.jpg");
        
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(lblImagen.getWidth(), lblImagen.getHeight(), Image.SCALE_DEFAULT));
        
        lblImagen.setIcon(icono);
        
        this.repaint();  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCliente = new javax.swing.JPanel();
        txtCodigo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        lblApellidos = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        txtTelefono1 = new javax.swing.JTextField();
        lblDireccion = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        txtFecha = new javax.swing.JFormattedTextField();
        pnlServicios = new javax.swing.JPanel();
        lblImagen = new javax.swing.JLabel();
        spPresupuesto = new javax.swing.JScrollPane();
        jtPresupuesto = new javax.swing.JTable();
        cbTrabajo = new javax.swing.JComboBox();
        btnAgregar = new javax.swing.JButton();
        spnCantidad = new javax.swing.JSpinner();
        btnQuitar = new javax.swing.JButton();
        pnlAcciones = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnLimpiartodo = new javax.swing.JButton();
        Menu = new javax.swing.JMenuBar();
        Acciones = new javax.swing.JMenu();
        cbMostrarImagenesMenu = new javax.swing.JCheckBoxMenuItem();
        cbGuardar = new javax.swing.JMenuItem();
        Salir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        pnlCliente.setBackground(new java.awt.Color(204, 204, 204));
        pnlCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 107, 107)), "CLIENTE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        txtCodigo.setToolTipText("Número de cliente de 5 dígitos.");
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rmed(evt);
            }
        });
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoKeyTyped(evt);
            }
        });

        txtNombre.setToolTipText("Nombre cliente. Max.20 Carac.");
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        txtApellido.setToolTipText("Apell. cliente.Max.30 Cara.");
        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoKeyTyped(evt);
            }
        });

        lblApellidos.setText("Apellidos:");

        lblNombre.setText("Nombre: ");

        lblCodigo.setText("Nº Cliente:");

        lblFecha.setText("Fecha:");

        lblTelefono.setText("Teléfono:");

        txtTelefono1.setToolTipText("NºTeléfono.Max.9 Carac");
        txtTelefono1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefono1KeyTyped(evt);
            }
        });

        lblDireccion.setText("Dirección:");

        txtDireccion.setToolTipText("Dirección cliente.Max.30 Carac.");

        txtFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        txtFecha.setToolTipText("El formato de fecha ha de ser:DD/MM/AAAA.");
        txtFecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFechaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout pnlClienteLayout = new javax.swing.GroupLayout(pnlCliente);
        pnlCliente.setLayout(pnlClienteLayout);
        pnlClienteLayout.setHorizontalGroup(
            pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCodigo)
                    .addComponent(lblDireccion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlClienteLayout.createSequentialGroup()
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlClienteLayout.createSequentialGroup()
                        .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(lblTelefono)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblFecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFecha)))
                .addGap(18, 18, 18))
        );
        pnlClienteLayout.setVerticalGroup(
            pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClienteLayout.createSequentialGroup()
                .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCodigo)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblApellidos)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccion)
                    .addComponent(lblFecha)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefono)
                    .addComponent(txtTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        pnlServicios.setBackground(new java.awt.Color(204, 204, 204));
        pnlServicios.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 107, 107)), "PRESUPUESTO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        lblImagen.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblImagen.setMaximumSize(new java.awt.Dimension(2, 2));
        lblImagen.setMinimumSize(new java.awt.Dimension(2, 2));
        lblImagen.setName(""); // NOI18N

        jtPresupuesto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Trabajo", "Cantidad", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spPresupuesto.setViewportView(jtPresupuesto);

        cbTrabajo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Instalación de Plato de ducha ", "Aplicar masilla y pintura", "División de tabiques", "Retirada de Escombros " }));
        cbTrabajo.setToolTipText("Tipos de trabajos.");
        cbTrabajo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbTrabajoItemStateChanged(evt);
            }
        });

        btnAgregar.setBackground(new java.awt.Color(204, 204, 204));
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/u04_usabilidad02/recursos/sub_black_add_2.png"))); // NOI18N
        btnAgregar.setToolTipText("Añadir nuevo trabajo");
        btnAgregar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnAgregar.setContentAreaFilled(false);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        spnCantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        spnCantidad.setToolTipText("Cantidad de trabajos");

        btnQuitar.setBackground(new java.awt.Color(204, 204, 204));
        btnQuitar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/u04_usabilidad02/recursos/sub_black_remove.png"))); // NOI18N
        btnQuitar.setToolTipText("Selecciona una línea del presupuesto y pulsa para eliminarla.");
        btnQuitar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnQuitar.setContentAreaFilled(false);
        btnQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlServiciosLayout = new javax.swing.GroupLayout(pnlServicios);
        pnlServicios.setLayout(pnlServiciosLayout);
        pnlServiciosLayout.setHorizontalGroup(
            pnlServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(pnlServiciosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlServiciosLayout.createSequentialGroup()
                        .addComponent(spPresupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlServiciosLayout.createSequentialGroup()
                        .addComponent(btnQuitar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbTrabajo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlServiciosLayout.createSequentialGroup()
                                .addComponent(spnCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(106, 106, 106))))))
        );
        pnlServiciosLayout.setVerticalGroup(
            pnlServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlServiciosLayout.createSequentialGroup()
                .addGroup(pnlServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(spPresupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlServiciosLayout.createSequentialGroup()
                        .addComponent(cbTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                            .addComponent(spnCantidad)))
                    .addGroup(pnlServiciosLayout.createSequentialGroup()
                        .addComponent(btnQuitar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pnlAcciones.setBackground(new java.awt.Color(204, 204, 204));
        pnlAcciones.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 107, 107))));

        btnGuardar.setBackground(new java.awt.Color(204, 204, 204));
        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/u04_usabilidad02/recursos/sub_black_accept.png"))); // NOI18N
        btnGuardar.setToolTipText("Guarda el presupuesto");
        btnGuardar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(204, 204, 204));
        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setToolTipText("Salir del formulario.  Se pasará a la pantalla de inicio.");
        btnSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalir.setContentAreaFilled(false);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnLimpiartodo.setBackground(new java.awt.Color(204, 204, 204));
        btnLimpiartodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/u04_usabilidad02/recursos/gnome_edit_delete.png"))); // NOI18N
        btnLimpiartodo.setToolTipText("Limpiar todo.");
        btnLimpiartodo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLimpiartodo.setContentAreaFilled(false);
        btnLimpiartodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiartodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAccionesLayout = new javax.swing.GroupLayout(pnlAcciones);
        pnlAcciones.setLayout(pnlAccionesLayout);
        pnlAccionesLayout.setHorizontalGroup(
            pnlAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAccionesLayout.createSequentialGroup()
                .addComponent(btnLimpiartodo, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlAccionesLayout.setVerticalGroup(
            pnlAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnGuardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnLimpiartodo, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
        );

        Acciones.setText("Acciones");

        cbMostrarImagenesMenu.setSelected(true);
        cbMostrarImagenesMenu.setText("Mostrar imágenes");
        cbMostrarImagenesMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMostrarImagenesMenuActionPerformed(evt);
            }
        });
        Acciones.add(cbMostrarImagenesMenu);

        cbGuardar.setText("Guardar");
        cbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGuardarActionPerformed(evt);
            }
        });
        Acciones.add(cbGuardar);

        Salir.setText("Salir");
        Salir.setToolTipText("Salir del programa.");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        Acciones.add(Salir);

        Menu.add(Acciones);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlServicios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pnlAcciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlServicios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlAcciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbTrabajoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbTrabajoItemStateChanged
        // TODO add your handling code here:
        ImageIcon imagen=new ImageIcon();
        
        if(cbMostrarImagenesMenu.getState()==true){
        
            switch(cbTrabajo.getSelectedIndex()){
            
                case 0:
                
                    imagen=new ImageIcon("recursos/EJ01_02.jpg");
                
                    break;
                    
                case 1:
                
                    imagen=new ImageIcon("recursos/EJ01_03.jpg");
                
                    break;
            
                case 2:
                
                    imagen=new ImageIcon("recursos/EJ01_04.jpg");
                
                    break;
            
                case 3:
                
                    imagen=new ImageIcon("recursos/EJ01_05.jpg");
                
                    break;
            }
            
            Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(lblImagen.getWidth(), lblImagen.getHeight(), Image.SCALE_DEFAULT));
        
            lblImagen.setIcon(icono);
        
            this.repaint(); 
        
        }else{
            
            switch(cbTrabajo.getSelectedIndex()){
            
                case 0:
                
                    imagen=new ImageIcon("recursos/EJ01_01.jpg");
                
                    break;
            
                case 1:
                
                    imagen=new ImageIcon("recursos/EJ01_01.jpg");
               
                    break;
            
                case 2:
                
                    imagen=new ImageIcon("recursos/EJ01_01.jpg");
                
                    break;
            
                case 3:
                
                    imagen=new ImageIcon("recursos/EJ01_01.jpg");
                
                    break;
            }
            
            Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(lblImagen.getWidth(), lblImagen.getHeight(), Image.SCALE_DEFAULT));
        
            lblImagen.setIcon(icono);
        
            this.repaint();
        
        }
        
    }//GEN-LAST:event_cbTrabajoItemStateChanged

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm=(DefaultTableModel) jtPresupuesto.getModel();
        
        switch(cbTrabajo.getSelectedIndex()){
            
            case 0:
                
                dtm.addRow(new Object[]{"Instalación plato de ducha", spnCantidad.getValue(), "19.5"});
                
                break;
            
            case 1:
                
                dtm.addRow(new Object[]{"Aplicar masilla y pintura", spnCantidad.getValue(), "12.10"});
                
                break;
            
            case 2:
                
                dtm.addRow(new Object[]{"División de tabiques", spnCantidad.getValue(), "15.99"});
                
                break;
            
            case 3:
                
                dtm.addRow(new Object[]{"Retirada de Escombros", spnCantidad.getValue(), "10.99"});
                
                break;
        
        }
        
        JOptionPane.showMessageDialog(null,"Trabajo agregado.");
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        guardar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        // TODO add your handling code here:
        char TestChar=evt.getKeyChar();
        
        if(!(Character.isLetter(TestChar)) && TestChar!=KeyEvent.VK_SPACE ||  txtNombre.getText().length() >= 20)
        
        {
            
            evt.consume();
        
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyTyped
        // TODO add your handling code here:
        char TestChar=evt.getKeyChar();
        
        if(!(Character.isDigit(TestChar))||txtCodigo.getText().length() >= 5)
       
        {
            
            evt.consume();
        
        }
    }//GEN-LAST:event_txtCodigoKeyTyped

    private void txtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyTyped
        // TODO add your handling code here:
        char TestChar=evt.getKeyChar();
        
        if(!(Character.isLetter(TestChar)) && TestChar!=KeyEvent.VK_SPACE ||  txtApellido.getText().length() >= 30)
        
        {
            
            evt.consume();
        
        }
    }//GEN-LAST:event_txtApellidoKeyTyped

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
    if(txtCodigo.getText().length()>0 || 
            txtNombre.getText().length()>0 || 
            txtApellido.getText().length()>0 || 
            txtDireccion.getText().length()>0 || 
            txtFecha.getText().length()>0|| 
            txtTelefono1.getText().length()>0||
            txtFecha.getText().length()>0||
            jtPresupuesto.getRowCount()>0){
            int respuesta = JOptionPane.showConfirmDialog(this, "¿Quiere salir sin guardar los cambios?", "Salir", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (respuesta == JOptionPane.YES_OPTION) {
                limpiarFormulario();
                dispose();

            }
        }
        else{
            //JOptionPane.showMessageDialog(null, "¡Adiós!");
            
            dispose();  //Sale porque no se han introducido datos. En este caso se cierra la ventana pero no la máquina virtual de java.
            
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void cbMostrarImagenesMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMostrarImagenesMenuActionPerformed
        // TODO add your handling code here:
        ImageIcon imagen=new ImageIcon();
        
        Icon icono;
        
        if (!this.cbMostrarImagenesMenu.getState()){
            
            imagen=new ImageIcon("recursos/EJ01_01.jpg");
            
            icono=new ImageIcon(imagen.getImage().getScaledInstance(lblImagen.getWidth(), lblImagen.getHeight(), Image.SCALE_DEFAULT));
            
            lblImagen.setIcon(icono);
           
            this.repaint(); }else{switch(cbTrabajo.getSelectedIndex()){
               
                case 0:
                    
                    imagen=new ImageIcon("recursos/EJ01_02.jpg");
                    
                    break;
                
                case 1:
                    
                    imagen=new ImageIcon("recursos/EJ01_03.jpg");
                    
                    break;
                
                case 2:
                    
                    imagen=new ImageIcon("recursos/EJ01_04.jpg");
                    
                    break;
                
                case 3:
                    
                    imagen=new ImageIcon("recursos/EJ01_05.jpg");
                    
                    break;
            
            }
            
            icono=new ImageIcon(imagen.getImage().getScaledInstance(lblImagen.getWidth(), lblImagen.getHeight(), Image.SCALE_DEFAULT));
            
            lblImagen.setIcon(icono);
            
            this.repaint();
        
        }   
  
    }//GEN-LAST:event_cbMostrarImagenesMenuActionPerformed

    private void cbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGuardarActionPerformed
        // TODO add your handling code here:
        guardar();
    }//GEN-LAST:event_cbGuardarActionPerformed

    private void txtTelefono1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefono1KeyTyped
        // TODO add your handling code here:
        if (txtTelefono1.getText().length()>=9)
        
        {
           
            evt.consume();
        
        }
        
    }//GEN-LAST:event_txtTelefono1KeyTyped

    private void rmed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rmed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_rmed

    private void txtFechaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaKeyTyped
        // TODO add your handling code here:
        if (txtFecha.getText().length()>=10)
        
        {
            
            evt.consume();
        
        }
    }//GEN-LAST:event_txtFechaKeyTyped

    private void btnQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarActionPerformed
      // TODO add your handling code here:
      DefaultTableModel dtm=(DefaultTableModel) jtPresupuesto.getModel();
      
      if (jtPresupuesto.getSelectedRow()!=-1){
          
          dtm.removeRow(jtPresupuesto.getSelectedRow());
          
          JOptionPane.showMessageDialog(null, "Fila eliminada");
      
      } else {
          
          JOptionPane.showMessageDialog(null, "No se ha seleccionado ninguna fila para eliminar");}
    }//GEN-LAST:event_btnQuitarActionPerformed

    private void btnLimpiartodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiartodoActionPerformed
        // TODO add your handling code here:
        limpiarFormulario();
        
        JOptionPane.showMessageDialog(null, "Formulario limpiado");
    }//GEN-LAST:event_btnLimpiartodoActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        if(txtCodigo.getText().length()>0 || 
            txtNombre.getText().length()>0 || 
            txtApellido.getText().length()>0 || 
            txtDireccion.getText().length()>0 || 
            txtFecha.getText().length()>0|| 
            txtTelefono1.getText().length()>0||
            txtFecha.getText().length()>0||
            jtPresupuesto.getRowCount()>0){
            int respuesta = JOptionPane.showConfirmDialog(this, "¿Quiere salir sin guardar los cambios?", "Salir", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (respuesta == JOptionPane.YES_OPTION) {
                limpiarFormulario();
                dispose();

            }
        }
        else{
            JOptionPane.showMessageDialog(null, "¡Adiós!");
            
            System.exit(0);  //Sale porque no se han introducido datos. En este caso se sale de la máquina virtual de java.
            
        }
        
    }//GEN-LAST:event_SalirActionPerformed
    
    //Método para limpiar el formulario
    void limpiarFormulario(){
        
        Component[] componentesClientes = pnlCliente.getComponents();
        
        for (int i = 0; i < componentesClientes.length; i++) {
            
            if(componentesClientes[i] instanceof JTextField){
                
                ((JTextField) componentesClientes[i]).setText("");
            
            }
            
            else if(componentesClientes[i] instanceof JFormattedTextField){
                
                ((JFormattedTextField) componentesClientes[i]).setText("");
            
            }
        
        }
     
        DefaultTableModel model = (DefaultTableModel) this.jtPresupuesto.getModel();
       // int[] rows = jtProductos.getSelectedRows();
        int rowslong = model.getRowCount();
        // i=1, 0  i=2 , 1 i=3 2 i=4 3
        for (int i = rowslong; i > 0; i--) {
            
            model.removeRow(i-1);
           
        }
       
    }
    
    //Método para guardar el formulario y comprobar su validación
    void guardar(){
            String errores="";
        String codigo=txtCodigo.getText().toUpperCase();
        String nombre=txtNombre.getText().toUpperCase();
        String apellidos=txtApellido.getText().toUpperCase();
        String direccion=txtDireccion.getText().toUpperCase();
        String telefono=txtTelefono1.getText().toUpperCase();
        String fecha=txtFecha.getText().toUpperCase();
       
        
        
        if (!codigo.matches("[0-9]{1,5}") || codigo.isEmpty()) errores+="\n-Error en Nº Cliente. Número de cliente vacío.";
        if (!nombre.matches("[A-Z]*[\\s[A-Z]*]*") || nombre.isEmpty()) errores+="\n-Error en Nombre. Nombre vacío";
        if (!apellidos.matches("[A-Z]*[\\s[A-Z]*]*") || apellidos.isEmpty()) errores+="\n-Error en Apellidos. Apellidos vacíos";
        if (!direccion.matches("[A-Z]*[\\s[A-Z]*]*[0-9]*") || direccion.isEmpty()) errores+="\n-Error en Dirección. Dirección vacía.";
        if (!telefono.matches("[0-9]*") ||telefono.length()<9|| telefono.isEmpty()) errores+="\n-Error en Teléfono.9 Dígitos";
        if (!fecha.matches("[0-9]{2}/[0-9]{2}/[0-9]{4}") ||fecha.length()<10||fecha.isEmpty()) errores+="\n-Error en Fecha. Formato dd/mm/aaaa";
        if (jtPresupuesto.getRowCount()==0) errores+="\n-Error en Presupuesto de trabajos. No se añadió ningún trabajo";
        
       
        
        if(errores.isEmpty()){
            System.out.println("Registro Guardado");
            JOptionPane.showMessageDialog(null,"Registro guardado.");
            limpiarFormulario();
            System.exit(0);
        }
        else{
            System.out.println("Errores: " + errores);
            JOptionPane.showMessageDialog(null,errores);
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntroducirReforma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntroducirReforma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntroducirReforma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntroducirReforma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                IntroducirReforma dialog = new IntroducirReforma(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Acciones;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenuItem Salir;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiartodo;
    private javax.swing.JButton btnQuitar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JMenuItem cbGuardar;
    private javax.swing.JCheckBoxMenuItem cbMostrarImagenesMenu;
    private javax.swing.JComboBox cbTrabajo;
    private javax.swing.JTable jtPresupuesto;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JPanel pnlAcciones;
    private javax.swing.JPanel pnlCliente;
    private javax.swing.JPanel pnlServicios;
    private javax.swing.JScrollPane spPresupuesto;
    private javax.swing.JSpinner spnCantidad;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JFormattedTextField txtFecha;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono1;
    // End of variables declaration//GEN-END:variables
}
