/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

/**
 *
 * @author benmu
 */
public class FormularioPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FormularioPrincipal
     */
    public FormularioPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel1 = new javax.swing.JPanel();
        BotonNuevaReforma = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();
        BarrraMenu = new javax.swing.JMenuBar();
        MenuRefor = new javax.swing.JMenu();
        NuevaReforma = new javax.swing.JMenuItem();
        Separador = new javax.swing.JPopupMenu.Separator();
        Salir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonNuevaReforma.setBackground(new java.awt.Color(255, 255, 255));
        BotonNuevaReforma.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        BotonNuevaReforma.setText("Nueva Reforma");
        BotonNuevaReforma.setToolTipText("Click. Para iniciar una nueva reforma");
        BotonNuevaReforma.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Click.Iniciar Reforma", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 0, 11))); // NOI18N
        BotonNuevaReforma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonNuevaReforma.setHideActionText(true);
        BotonNuevaReforma.setMultiClickThreshhold(1L);
        BotonNuevaReforma.setName(""); // NOI18N
        BotonNuevaReforma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonNuevaReformaActionPerformed(evt);
            }
        });
        Panel1.add(BotonNuevaReforma, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 90, 40));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/construcion_jpg.jpg"))); // NOI18N
        Panel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 310));

        BarrraMenu.setBackground(new java.awt.Color(255, 255, 255));
        BarrraMenu.setAutoscrolls(true);
        BarrraMenu.setDoubleBuffered(true);
        BarrraMenu.setFocusCycleRoot(true);
        BarrraMenu.setFocusTraversalPolicyProvider(true);
        BarrraMenu.setInheritsPopupMenu(true);

        MenuRefor.setBackground(new java.awt.Color(255, 255, 255));
        MenuRefor.setText("Gestionar Reformas");
        MenuRefor.setToolTipText("Menú");
        MenuRefor.setAutoscrolls(true);
        MenuRefor.setBorderPainted(true);
        MenuRefor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuRefor.setDoubleBuffered(true);
        MenuRefor.setFocusCycleRoot(true);
        MenuRefor.setFocusPainted(true);
        MenuRefor.setFocusTraversalPolicyProvider(true);
        MenuRefor.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        MenuRefor.setHideActionText(true);
        MenuRefor.setInheritsPopupMenu(true);
        MenuRefor.setOpaque(true);

        NuevaReforma.setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N
        NuevaReforma.setText("Nueva Reforma");
        NuevaReforma.setToolTipText("Iniciar nueva reforma");
        NuevaReforma.setActionCommand("Nueva reforma");
        NuevaReforma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NuevaReforma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevaReformaActionPerformed(evt);
            }
        });
        MenuRefor.add(NuevaReforma);
        MenuRefor.add(Separador);

        Salir.setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N
        Salir.setText("Salir");
        Salir.setToolTipText("Salir del programa");
        Salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        MenuRefor.add(Salir);

        BarrraMenu.add(MenuRefor);

        setJMenuBar(BarrraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NuevaReformaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevaReformaActionPerformed
        // TODO add your handling code here:
        FormularioDatos formulariodatos = new FormularioDatos (this,true);
        formulariodatos.setVisible(true);
    }//GEN-LAST:event_NuevaReformaActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_SalirActionPerformed

    private void BotonNuevaReformaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonNuevaReformaActionPerformed
        // TODO add your handling code here:
        FormularioDatos formulariodatos = new FormularioDatos (this,true);
        formulariodatos.setVisible(true);
    }//GEN-LAST:event_BotonNuevaReformaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarrraMenu;
    private javax.swing.JButton BotonNuevaReforma;
    private javax.swing.JLabel Fondo;
    private javax.swing.JMenu MenuRefor;
    private javax.swing.JMenuItem NuevaReforma;
    private javax.swing.JPanel Panel1;
    private javax.swing.JMenuItem Salir;
    private javax.swing.JPopupMenu.Separator Separador;
    // End of variables declaration//GEN-END:variables
}
