/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;


import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;


/**
 *
 * @author benmu
 */
public class FormularioDatos extends javax.swing.JDialog {

    /**
     * Creates new form FormularioDatos
     */
    public FormularioDatos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        /*Pongo el spinner no activo al principio, para que no pueda ser modificado
        hasta que se selecciones el jcombobox(encargados)*/
        spinner.setEnabled(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        FormularioDatos = new javax.swing.JPanel();
        PanelDatosCliente = new javax.swing.JPanel();
        codigo = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        apellidos = new javax.swing.JTextField();
        direccion = new javax.swing.JTextField();
        telefono = new javax.swing.JTextField();
        fecha = new javax.swing.JFormattedTextField();
        codigoLabel = new javax.swing.JLabel();
        nombreLabel = new javax.swing.JLabel();
        direccionLabel = new javax.swing.JLabel();
        apellidosLabel = new javax.swing.JLabel();
        telefonoLabel = new javax.swing.JLabel();
        fechaLabel = new javax.swing.JLabel();
        PanelTipoReforma = new javax.swing.JPanel();
        reformaIntegral = new javax.swing.JRadioButton();
        sanitarios = new javax.swing.JRadioButton();
        pavimento = new javax.swing.JRadioButton();
        jSeparator2 = new javax.swing.JSeparator();
        estructura = new javax.swing.JRadioButton();
        cimentacion = new javax.swing.JRadioButton();
        albañileria = new javax.swing.JRadioButton();
        fontaneria = new javax.swing.JRadioButton();
        decoracion = new javax.swing.JRadioButton();
        carpinteria = new javax.swing.JRadioButton();
        albañileriaSani = new javax.swing.JRadioButton();
        fontaneriaSani = new javax.swing.JRadioButton();
        decoracionSani = new javax.swing.JRadioButton();
        estructuraPavi = new javax.swing.JRadioButton();
        cimentacionPavi = new javax.swing.JRadioButton();
        Deshacer = new javax.swing.JButton();
        PanelEncargado1 = new javax.swing.JPanel();
        encargado = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        coste = new javax.swing.JFormattedTextField();
        spinner = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        guardar = new javax.swing.JButton();
        salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        FormularioDatos.setBackground(new java.awt.Color(255, 255, 255));
        FormularioDatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelDatosCliente.setBackground(new java.awt.Color(255, 255, 255));
        PanelDatosCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS DEL CLIENTE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 14))); // NOI18N
        PanelDatosCliente.setPreferredSize(new java.awt.Dimension(600, 200));

        codigo.setToolTipText("Código de 5 digitos numéricos.");
        codigo.setMinimumSize(new java.awt.Dimension(5, 5));
        codigo.setName(""); // NOI18N
        codigo.setPreferredSize(new java.awt.Dimension(5, 5));
        codigo.setSelectionColor(new java.awt.Color(0, 0, 0));
        codigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                codigoKeyTyped(evt);
            }
        });

        nombre.setToolTipText("Nombre. Máximo 20 caracteres");
        nombre.setMaximumSize(new java.awt.Dimension(5, 5));
        nombre.setMinimumSize(new java.awt.Dimension(5, 5));
        nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreKeyTyped(evt);
            }
        });

        apellidos.setToolTipText("Apellido.Máximo 30 caracteres");
        apellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                apellidosKeyTyped(evt);
            }
        });

        direccion.setToolTipText("Dirección.Máximo 30 caracteres");
        direccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                direccionKeyTyped(evt);
            }
        });

        telefono.setToolTipText("Teléfono de contacto.Máximo 9 caracteres. Digitos.");
        telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telefonoKeyTyped(evt);
            }
        });

        fecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        fecha.setToolTipText("El formato de fecha ha de ser:DD/MM/AAAA.");
        fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaActionPerformed(evt);
            }
        });
        fecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fechaKeyTyped(evt);
            }
        });

        codigoLabel.setFont(new java.awt.Font("Agency FB", 1, 12)); // NOI18N
        codigoLabel.setText("Código:");

        nombreLabel.setFont(new java.awt.Font("Agency FB", 1, 12)); // NOI18N
        nombreLabel.setText("Nombre:");

        direccionLabel.setFont(new java.awt.Font("Agency FB", 1, 12)); // NOI18N
        direccionLabel.setText("Dirección:");

        apellidosLabel.setFont(new java.awt.Font("Agency FB", 1, 12)); // NOI18N
        apellidosLabel.setText("Apellidos:");

        telefonoLabel.setFont(new java.awt.Font("Agency FB", 1, 12)); // NOI18N
        telefonoLabel.setText("Teléfono de contacto:");

        fechaLabel.setFont(new java.awt.Font("Agency FB", 1, 12)); // NOI18N
        fechaLabel.setText("Fecha de alta:");

        javax.swing.GroupLayout PanelDatosClienteLayout = new javax.swing.GroupLayout(PanelDatosCliente);
        PanelDatosCliente.setLayout(PanelDatosClienteLayout);
        PanelDatosClienteLayout.setHorizontalGroup(
            PanelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDatosClienteLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(PanelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(codigoLabel)
                    .addComponent(nombreLabel)
                    .addComponent(apellidosLabel)
                    .addComponent(direccionLabel)
                    .addComponent(telefonoLabel)
                    .addComponent(fechaLabel))
                .addGroup(PanelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDatosClienteLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(PanelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(telefono, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(direccion, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(fecha)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDatosClienteLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(PanelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(apellidos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codigo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        PanelDatosClienteLayout.setVerticalGroup(
            PanelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDatosClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoLabel)
                    .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apellidosLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(direccionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefonoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        FormularioDatos.add(PanelDatosCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 400, 250));

        PanelTipoReforma.setBackground(new java.awt.Color(255, 255, 255));
        PanelTipoReforma.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TIPO DE REFORMA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 14))); // NOI18N

        reformaIntegral.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(reformaIntegral);
        reformaIntegral.setFont(new java.awt.Font("Agency FB", 1, 12)); // NOI18N
        reformaIntegral.setText("REFORMA INTEGRAL");
        reformaIntegral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reformaIntegralActionPerformed(evt);
            }
        });

        sanitarios.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(sanitarios);
        sanitarios.setFont(new java.awt.Font("Agency FB", 1, 12)); // NOI18N
        sanitarios.setText("SANITARIOS");
        sanitarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sanitariosActionPerformed(evt);
            }
        });

        pavimento.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(pavimento);
        pavimento.setFont(new java.awt.Font("Agency FB", 1, 12)); // NOI18N
        pavimento.setText("PAVIMENTO");
        pavimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pavimentoActionPerformed(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        estructura.setBackground(new java.awt.Color(255, 255, 255));
        estructura.setFont(new java.awt.Font("Agency FB", 1, 12)); // NOI18N
        estructura.setText("Estructura");
        estructura.setEnabled(false);

        cimentacion.setBackground(new java.awt.Color(255, 255, 255));
        cimentacion.setFont(new java.awt.Font("Agency FB", 1, 12)); // NOI18N
        cimentacion.setText("Cimentación");
        cimentacion.setEnabled(false);

        albañileria.setBackground(new java.awt.Color(255, 255, 255));
        albañileria.setFont(new java.awt.Font("Agency FB", 1, 12)); // NOI18N
        albañileria.setText("Albañilería");
        albañileria.setEnabled(false);

        fontaneria.setBackground(new java.awt.Color(255, 255, 255));
        fontaneria.setFont(new java.awt.Font("Agency FB", 1, 12)); // NOI18N
        fontaneria.setText("Fontanería");
        fontaneria.setEnabled(false);

        decoracion.setBackground(new java.awt.Color(255, 255, 255));
        decoracion.setFont(new java.awt.Font("Agency FB", 1, 12)); // NOI18N
        decoracion.setText("Decoración");
        decoracion.setEnabled(false);

        carpinteria.setBackground(new java.awt.Color(255, 255, 255));
        carpinteria.setFont(new java.awt.Font("Agency FB", 1, 12)); // NOI18N
        carpinteria.setText("Carpintería");
        carpinteria.setEnabled(false);

        albañileriaSani.setBackground(new java.awt.Color(255, 255, 255));
        albañileriaSani.setFont(new java.awt.Font("Agency FB", 1, 12)); // NOI18N
        albañileriaSani.setText("Albañilería");
        albañileriaSani.setEnabled(false);

        fontaneriaSani.setBackground(new java.awt.Color(255, 255, 255));
        fontaneriaSani.setFont(new java.awt.Font("Agency FB", 1, 12)); // NOI18N
        fontaneriaSani.setText("Fontanería");
        fontaneriaSani.setEnabled(false);

        decoracionSani.setBackground(new java.awt.Color(255, 255, 255));
        decoracionSani.setFont(new java.awt.Font("Agency FB", 1, 12)); // NOI18N
        decoracionSani.setText("Decoración");
        decoracionSani.setEnabled(false);

        estructuraPavi.setBackground(new java.awt.Color(255, 255, 255));
        estructuraPavi.setFont(new java.awt.Font("Agency FB", 1, 12)); // NOI18N
        estructuraPavi.setText("Estructura");
        estructuraPavi.setEnabled(false);

        cimentacionPavi.setBackground(new java.awt.Color(255, 255, 255));
        cimentacionPavi.setFont(new java.awt.Font("Agency FB", 1, 12)); // NOI18N
        cimentacionPavi.setText("Cimentación");
        cimentacionPavi.setEnabled(false);

        javax.swing.GroupLayout PanelTipoReformaLayout = new javax.swing.GroupLayout(PanelTipoReforma);
        PanelTipoReforma.setLayout(PanelTipoReformaLayout);
        PanelTipoReformaLayout.setHorizontalGroup(
            PanelTipoReformaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTipoReformaLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(PanelTipoReformaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelTipoReformaLayout.createSequentialGroup()
                        .addGroup(PanelTipoReformaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(estructura)
                            .addComponent(reformaIntegral)
                            .addComponent(cimentacion)
                            .addComponent(albañileria)
                            .addComponent(fontaneria)
                            .addComponent(decoracion))
                        .addGap(31, 31, 31)
                        .addGroup(PanelTipoReformaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelTipoReformaLayout.createSequentialGroup()
                                .addGroup(PanelTipoReformaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(sanitarios, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(decoracionSani, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelTipoReformaLayout.createSequentialGroup()
                                .addGroup(PanelTipoReformaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(albañileriaSani, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fontaneriaSani, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(PanelTipoReformaLayout.createSequentialGroup()
                        .addComponent(carpinteria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(PanelTipoReformaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(estructuraPavi)
                    .addComponent(pavimento)
                    .addComponent(cimentacionPavi))
                .addGap(24, 24, 24)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PanelTipoReformaLayout.setVerticalGroup(
            PanelTipoReformaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTipoReformaLayout.createSequentialGroup()
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelTipoReformaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelTipoReformaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelTipoReformaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(reformaIntegral, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(sanitarios))
                    .addComponent(pavimento, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(PanelTipoReformaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelTipoReformaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(estructura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cimentacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(albañileria))
                    .addGroup(PanelTipoReformaLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(PanelTipoReformaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(estructuraPavi)
                            .addComponent(albañileriaSani))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelTipoReformaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cimentacionPavi)
                            .addComponent(fontaneriaSani))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(decoracionSani)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fontaneria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(decoracion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(carpinteria)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        FormularioDatos.add(PanelTipoReforma, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 400, 250));

        Deshacer.setBackground(new java.awt.Color(255, 255, 255));
        Deshacer.setText("Deshacer selección");
        Deshacer.setToolTipText("Eliminar selección de Tipo de Reforma.");
        Deshacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeshacerActionPerformed(evt);
            }
        });
        FormularioDatos.add(Deshacer, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 280, 150, 30));

        PanelEncargado1.setBackground(new java.awt.Color(255, 255, 255));
        PanelEncargado1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ENCARGADO DE LA REFORMA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 14))); // NOI18N

        encargado.setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N
        encargado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Empleados propios", "Autónomos", "Subcontrata" }));
        encargado.setToolTipText("Seleccionar  a los encargados de la reforma.");
        encargado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encargadoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 12)); // NOI18N
        jLabel1.setText("TIPO DE ENCARGADO");

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 12)); // NOI18N
        jLabel2.setText("COSTExHORA.MANO DE OBRA");

        try {
            coste.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##,##€")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        coste.setToolTipText("Coste por hora de la mano de obra.");

        spinner.setModel(new javax.swing.SpinnerNumberModel(2, 2, 50, 1));
        spinner.setToolTipText("Selecciona nº operarios");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 12)); // NOI18N
        jLabel3.setText("Nº OPERARIOS");

        javax.swing.GroupLayout PanelEncargado1Layout = new javax.swing.GroupLayout(PanelEncargado1);
        PanelEncargado1.setLayout(PanelEncargado1Layout);
        PanelEncargado1Layout.setHorizontalGroup(
            PanelEncargado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEncargado1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelEncargado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(encargado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(PanelEncargado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(PanelEncargado1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(coste, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(PanelEncargado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );
        PanelEncargado1Layout.setVerticalGroup(
            PanelEncargado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEncargado1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(PanelEncargado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelEncargado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(encargado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 23, Short.MAX_VALUE))
        );

        FormularioDatos.add(PanelEncargado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 400, 120));

        guardar.setBackground(new java.awt.Color(255, 255, 255));
        guardar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        guardar.setText("GUARDAR");
        guardar.setToolTipText("Pulsa para guardar registro e iniciar uno nuevo si todo es correcto.");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        FormularioDatos.add(guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 100, 50));

        salir.setBackground(new java.awt.Color(255, 255, 255));
        salir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        salir.setText("SALIR");
        salir.setToolTipText("Salir de nueva reforma.");
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirMouseClicked(evt);
            }
        });
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        FormularioDatos.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, 100, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FormularioDatos, javax.swing.GroupLayout.DEFAULT_SIZE, 885, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(FormularioDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed

        // TODO add your handling code here:
        /*Se comprueba que se cumplen las condiciones de la validación*/
        if (validarFormulario())
        {
            /*Todo vuelve a su forma original*/
            JOptionPane.showMessageDialog(this, "Registro guardado");

            /*Datos del cliente*/
            codigo.setText("");
            nombre.setText("");
            apellidos.setText("");
            direccion.setText("");
            telefono.setText ("");
            fecha.setText ("");

            /*Encargado de la reforma*/
            coste.setText("");
            encargado.setSelectedIndex(0);
            spinner.setValue(2);
            spinner.setEnabled(false);

            /*Tipo de reforma*/
            buttonGroup1.clearSelection();
            reformaIntegral.setEnabled(true);
            sanitarios.setEnabled(true);
            pavimento.setEnabled(true);
            estructura.setEnabled(true);
            cimentacion.setEnabled(true);
            albañileria.setEnabled(true);
            fontaneria.setEnabled(true);
            decoracion.setEnabled(true);
            carpinteria.setEnabled(true);
            albañileriaSani.setEnabled(true);
            fontaneriaSani.setEnabled(true);
            decoracionSani.setEnabled(true);
            estructuraPavi.setEnabled(true);
            cimentacionPavi.setEnabled(true);

            reformaIntegral.setSelected(false);
            sanitarios.setSelected(false);
            pavimento.setSelected(false);
            estructura.setSelected(false);
            cimentacion.setSelected(false);
            albañileria.setSelected(false);
            fontaneria.setSelected(false);
            decoracion.setSelected(false);
            carpinteria.setSelected(false);
            albañileriaSani.setSelected(false);
            fontaneriaSani.setSelected(false);
            decoracionSani.setSelected(false);
            estructuraPavi.setSelected(false);
            cimentacionPavi.setSelected(false);

            estructura.setEnabled(false);
            cimentacion.setEnabled(false);
            albañileria.setEnabled(false);
            fontaneria.setEnabled(false);
            decoracion.setEnabled(false);
            carpinteria.setEnabled(false);
            albañileriaSani.setEnabled(false);
            fontaneriaSani.setEnabled(false);
            decoracionSani.setEnabled(false);
            estructuraPavi.setEnabled(false);
            cimentacionPavi.setEnabled(false);
        }
    }//GEN-LAST:event_guardarActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:

        if (validacionSalir())
        {int n=JOptionPane.showConfirmDialog(null, "Has introducido algún dato de la sección 'Datos del Cliente', ¿QUIERES SALIR?","Vas a salir..",JOptionPane.ERROR_MESSAGE);
            if (n==0) {dispose();}
            if (n==1) {}
        }
    }//GEN-LAST:event_salirActionPerformed

    private void salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_salirMouseClicked

    private void encargadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encargadoActionPerformed
        // TODO add your handling code here:
        if (encargado.getSelectedItem().equals("Empleados propios")) {
            spinner.setEnabled(false);

        }

        if (encargado.getSelectedItem().equals("Autónomos")||encargado.getSelectedItem().equals("Subcontrata")) {
            spinner.setEnabled(true);
        }
    }//GEN-LAST:event_encargadoActionPerformed

    private void DeshacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeshacerActionPerformed
        // TODO add your handling code here:
        /*Se ponen activos todos los "jradiobutton"*/
        buttonGroup1.clearSelection();
        reformaIntegral.setEnabled(true);
        sanitarios.setEnabled(true);
        pavimento.setEnabled(true);
        estructura.setEnabled(true);
        cimentacion.setEnabled(true);
        albañileria.setEnabled(true);
        fontaneria.setEnabled(true);
        decoracion.setEnabled(true);
        carpinteria.setEnabled(true);
        albañileriaSani.setEnabled(true);
        fontaneriaSani.setEnabled(true);
        decoracionSani.setEnabled(true);
        estructuraPavi.setEnabled(true);
        cimentacionPavi.setEnabled(true);

        /*Se deselecciona todos los "jradiobutton"*/
        reformaIntegral.setSelected(false);
        sanitarios.setSelected(false);
        pavimento.setSelected(false);
        estructura.setSelected(false);
        cimentacion.setSelected(false);
        albañileria.setSelected(false);
        fontaneria.setSelected(false);
        decoracion.setSelected(false);
        carpinteria.setSelected(false);
        albañileriaSani.setSelected(false);
        fontaneriaSani.setSelected(false);
        decoracionSani.setSelected(false);
        estructuraPavi.setSelected(false);
        cimentacionPavi.setSelected(false);

        /*Se desactivan las reformas*/
        estructura.setEnabled(false);
        cimentacion.setEnabled(false);
        albañileria.setEnabled(false);
        fontaneria.setEnabled(false);
        decoracion.setEnabled(false);
        carpinteria.setEnabled(false);
        albañileriaSani.setEnabled(false);
        fontaneriaSani.setEnabled(false);
        decoracionSani.setEnabled(false);
        estructuraPavi.setEnabled(false);
        cimentacionPavi.setEnabled(false);
    }//GEN-LAST:event_DeshacerActionPerformed

    private void pavimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pavimentoActionPerformed
        // TODO add your handling code here:
        /*Si pavimento es seleccionado, se ponen activos los de su grupo y el resto siguen desactivados*/
        if (pavimento.isSelected())
        {
            reformaIntegral.setEnabled(false);
            sanitarios.setEnabled(false);
            estructura.setEnabled(false);
            cimentacion.setEnabled(false);
            albañileria.setEnabled(false);
            fontaneria.setEnabled(false);
            decoracion.setEnabled(false);
            carpinteria.setEnabled(false);
            albañileriaSani.setEnabled(false);
            fontaneriaSani.setEnabled(false);
            decoracionSani.setEnabled(false);
            estructuraPavi.setEnabled(true);
            cimentacionPavi.setEnabled(true);
        }
    }//GEN-LAST:event_pavimentoActionPerformed

    private void sanitariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sanitariosActionPerformed
        // TODO add your handling code here:
        /*Si sanitarios es seleccionado, se ponen activos los de su grupo y el resto siguen desactivados*/
        if (sanitarios.isSelected())
        {
            reformaIntegral.setEnabled(false);
            pavimento.setEnabled(false);
            estructura.setEnabled(false);
            cimentacion.setEnabled(false);
            albañileria.setEnabled(false);
            fontaneria.setEnabled(false);
            decoracion.setEnabled(false);
            carpinteria.setEnabled(false);
            albañileriaSani.setEnabled(true);
            fontaneriaSani.setEnabled(true);
            decoracionSani.setEnabled(true);
            estructuraPavi.setEnabled(false);
            cimentacionPavi.setEnabled(false);
        }
    }//GEN-LAST:event_sanitariosActionPerformed

    private void reformaIntegralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reformaIntegralActionPerformed
        // TODO add your handling code here:
        /*Si reformaIntegral es seleccionado, se ponen activos los de su grupo y el resto siguen desactivados*/
        if (reformaIntegral.isSelected())
        {
            estructura.setEnabled(true);
            cimentacion.setEnabled(true);
            albañileria.setEnabled(true);
            fontaneria.setEnabled(true);
            decoracion.setEnabled(true);
            carpinteria.setEnabled(true);
            sanitarios.setEnabled(false);
            pavimento.setEnabled(false);
            albañileriaSani.setEnabled(false);
            fontaneriaSani.setEnabled(false);
            decoracionSani.setEnabled(false);
            estructuraPavi.setEnabled(false);
            cimentacionPavi.setEnabled(false);

        }
    }//GEN-LAST:event_reformaIntegralActionPerformed

    private void fechaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fechaKeyTyped
        // TODO add your handling code here:
        if (fecha.getText().length()>=10)
        {
            evt.consume();
        }
    }//GEN-LAST:event_fechaKeyTyped

    private void fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaActionPerformed

    private void telefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefonoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (c<'0' || c>'9')evt.consume();

        if (telefono.getText().length()>=9)
        {
            evt.consume();
        }
    }//GEN-LAST:event_telefonoKeyTyped

    private void direccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_direccionKeyTyped
        // TODO add your handling code here:
        if (direccion.getText().length()>=30)
        {
            evt.consume();
        }
    }//GEN-LAST:event_direccionKeyTyped

    private void apellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apellidosKeyTyped
        // TODO add your handling code here:
        if (apellidos.getText().length()>=30)
        {
            evt.consume();
        }
    }//GEN-LAST:event_apellidosKeyTyped

    private void nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreKeyTyped
        // TODO add your handling code here:
        if (nombre.getText().length()>=20)
        {
            evt.consume();
        }
    }//GEN-LAST:event_nombreKeyTyped

    private void codigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (c<'0' || c>'9')evt.consume();

        if (codigo.getText().length()>=5)
        {
            evt.consume();
        }
    }//GEN-LAST:event_codigoKeyTyped
       
    private boolean validarFormulario (){
        String nom=nombre.getText();
        String ape=apellidos.getText();
        String dir=direccion.getText();
        String tel=telefono.getText();
        String fec=fecha.getText();
        String cos=coste.getText();

        /*VALIDACIÓN DE DATOS DE LOS CLIENTES*/
        try
        {
            Integer.parseInt(codigo.getText());
        }
        catch (NumberFormatException n)
        {
           JOptionPane.showMessageDialog(this, "El campo Código, no puede estar vacío", "ERROR", JOptionPane.ERROR_MESSAGE);
            return false;
            
        }


        if (nom==null||"".equals(nom))
        {
            JOptionPane.showMessageDialog(this, "El campo Nombre, no puede estar vacío", "ERROR", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        
        if (ape==null||"".equals(ape))
        {
            JOptionPane.showMessageDialog(this, "El campo Apellidos, no puede estar vacío", "ERROR", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        
        if (dir==null||"".equals(dir))
        {
            JOptionPane.showMessageDialog(this, "El campo Dirección, no puede estar vacío", "ERROR", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        
        if (tel==null||"".equals(tel)) 
        {
            JOptionPane.showMessageDialog(this, "El campo Teléfono de contacto, no puede estar vacío", "ERROR", JOptionPane.ERROR_MESSAGE);
            return false;
        }
                if (tel.length()<9) 
        {
            JOptionPane.showMessageDialog(this, "El campo Teléfono de contacto, ha de tener 9 dígitos", "ERROR", JOptionPane.ERROR_MESSAGE);
            return false;
        }
                
               try{
                   SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");
            formatoFecha.setLenient(false);
            formatoFecha.parse(fec); 
                        } catch (ParseException e) {JOptionPane.showMessageDialog(this, "El campo Fecha, no puede estar vacío y ha de tener el siguiente formato:Ej.12/10/2020", "ERROR", JOptionPane.ERROR_MESSAGE);
                        
            return false;
        
        }
        
               
        /*VALIDACIÓN TIPO DE REFORMA*/

        if (reformaIntegral.isSelected()==false && sanitarios.isSelected()==false && pavimento.isSelected()==false)
               {JOptionPane.showMessageDialog(this, "Debes seleccionar un tipo de reforma", "ERROR", JOptionPane.ERROR_MESSAGE);
            return false; 
               }
               
       if (estructura.isSelected()==false && cimentacion.isSelected()==false && albañileria.isSelected()==false&&
                          fontaneria.isSelected()==false && decoracion.isSelected()==false && carpinteria.isSelected()==false&&
                      albañileriaSani.isSelected()==false && fontaneriaSani.isSelected()==false && decoracionSani.isSelected()==false&&
                          estructuraPavi.isSelected()==false && cimentacionPavi.isSelected()==false)
               {JOptionPane.showMessageDialog(this, "Debes seleccionar alguno de los servicios de la reforma elegida", "ERROR", JOptionPane.ERROR_MESSAGE);
            return false; 
               } 
       
        if (cos==null||"  ,  €".equals(cos)) 
        {
            JOptionPane.showMessageDialog(this, "El campo CosteXHoraMano de obra, debe contener una cuantía", "ERROR", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
return true;       
}



private boolean validacionSalir (){
        String cod=codigo.getText();
        String nom=nombre.getText();
        String ape=apellidos.getText();
        String dir=direccion.getText();
        String tel=telefono.getText();
        String fec=fecha.getText();
  
        if (!nom.isEmpty() || !nom.isEmpty() || !nom.isEmpty() || !ape.isEmpty() || !dir.isEmpty() || !tel.isEmpty() || !fec.isEmpty()||!cod.isEmpty())
        {
            return true;
      }
   return false;     
}



    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormularioDatos dialog = new FormularioDatos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Deshacer;
    private javax.swing.JPanel FormularioDatos;
    private javax.swing.JPanel PanelDatosCliente;
    private javax.swing.JPanel PanelEncargado1;
    private javax.swing.JPanel PanelTipoReforma;
    private javax.swing.JRadioButton albañileria;
    private javax.swing.JRadioButton albañileriaSani;
    private javax.swing.JTextField apellidos;
    private javax.swing.JLabel apellidosLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton carpinteria;
    private javax.swing.JRadioButton cimentacion;
    private javax.swing.JRadioButton cimentacionPavi;
    private javax.swing.JTextField codigo;
    private javax.swing.JLabel codigoLabel;
    private javax.swing.JFormattedTextField coste;
    private javax.swing.JRadioButton decoracion;
    private javax.swing.JRadioButton decoracionSani;
    private javax.swing.JTextField direccion;
    private javax.swing.JLabel direccionLabel;
    private javax.swing.JComboBox<String> encargado;
    private javax.swing.JRadioButton estructura;
    private javax.swing.JRadioButton estructuraPavi;
    private javax.swing.JFormattedTextField fecha;
    private javax.swing.JLabel fechaLabel;
    private javax.swing.JRadioButton fontaneria;
    private javax.swing.JRadioButton fontaneriaSani;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField nombre;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JRadioButton pavimento;
    private javax.swing.JRadioButton reformaIntegral;
    private javax.swing.JButton salir;
    private javax.swing.JRadioButton sanitarios;
    private javax.swing.JSpinner spinner;
    private javax.swing.JTextField telefono;
    private javax.swing.JLabel telefonoLabel;
    // End of variables declaration//GEN-END:variables
}
